env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
language: rust
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.2.0"; then
      cargo install cargo-prune --vers="0.2.0" --force;
    fi
  - rustup component add rustfmt clippy
script:
  - set -x;
    cargo fmt -- --check &&
    cargo clippy --verbose --release --all-targets &&
    cargo test --verbose --release
before_cache:
  - cargo prune
