env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
language: rust
sudo: false
addons:
    apt:
        packages:
            - libssl-dev
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.2.0"; then
      cargo install cargo-prune --vers="0.2.0" --force;
    fi
  - rustup component add rustfmt clippy
script:
  - cargo fmt -- --check
  - cargo clippy --verbose --release --all-targets ;
  - cargo test --verbose --release
before_cache:
  - cargo prune
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
