name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    if: github.repository_owner == 'maidsafe'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
